### ISSUE TITLE
feature: treat bare caret as anchor instead of range negation

### ISSUE THREAD

**Issue by roycewilliams** [undeath/hcgrep#2]
Steps to reproduce:

$ cat test.list
123
1234
12345
abc
abc.d

$ hcgrep.py '^?d?d?d?d' test.list
abc.d

$

**Comment by undeath** [comment]
This is actually a bug, but not the kind you think it is. hcgrep doesn't try to re-invent hashcat masks and a `^` should always match a literal `^`. The option you are looking for is `--mask-match-mode s`.

Fixed on master.

```
$ cat test.lst
123
1234
12345
abc
abc.d
^1234
^abc.d
a^1234

$ hcgrep '^?d?d?d?d' test.lst       
^1234
a^1234

$ hcgrep '^?d?d?d?d' test.lst --mm s
^1234
```

**Comment by roycewilliams** [comment]
At 50 you'd think I'd RTFM before opening issues. :grimacing:  Thank you!
